import type { Metadata } from "next";
import localFont from "next/font/local";
import StyledComponentsRegistry from "@/GlobalStyles/registry";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

import { DM_Sans } from 'next/font/google';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const dmSans = DM_Sans({
  subsets: ['latin'],         // Subconjunto de caracteres (puedes ajustar según tus necesidades).
  weight: ['400', '500', '700'], // Pesos que necesitas (400: Regular, 500: Medium, 700: Bold).
  style: ['normal', 'italic'],   // Opcional: estilos adicionales como itálica.
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StyledComponentsRegistry>
      <body className={dmSans.className}>
      <Header/>
        {children}
        <Footer/>
      </body>
      </StyledComponentsRegistry>
    </html>
  );
}
