export const CAR_LIST = [
    {
        _id: 1,
        name: 'Corolla',
        year: 2024,
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa iste, magnam quae incidunt animi dolorum eveniet placeat corrupti!',
        brand: 'Toyota',
        model: 'Corolla',
        imgs: [
            'https://res.cloudinary.com/dfvznarq2/image/upload/v1736018265/toyotaC1_aq2teu.png', 'https://res.cloudinary.com/dfvznarq2/image/upload/v1736018266/toyotaC2_huio2n.png', 'https://res.cloudinary.com/dfvznarq2/image/upload/v1736018266/toyotaC3_po1ep8.png'
        ],
        cover: 'https://res.cloudinary.com/dfvznarq2/image/upload/v1736018265/toyotaC1_aq2teu.png',
        transmition: 'manual',
        fuel: 'petrol',
        isRented: false,
        isOnsale: false,
        price: 500,
        divisa: 'euro',
        bodyType: 'Sedan',
        mileage: 15000,
        color: 'White',
        trimLevel: 'SE Hybrid',
        engineCapacity: 1.8,
        doors: 4,
        passengerCapacity: 5,
        fuelConsumption: '7L/100km',
        location: 'Madrid, España',
        condition: 'Used',
        availabilityDate: '2024-11-01',
        features: ['airbags', 'ABS', 'GPS'],
        rating: 4.5,
       
    },
    {
        _id: 2,
        name: 'Corolla',
        year: 2024,
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa iste, magnam quae incidunt animi dolorum eveniet placeat corrupti!',
        brand: 'Toyota',
        model: 'Corolla',
        imgs: [
            'https://res.cloudinary.com/dfvznarq2/image/upload/v1736018265/toyotaC1_aq2teu.png', 'https://res.cloudinary.com/dfvznarq2/image/upload/v1736018266/toyotaC2_huio2n.png', 'https://res.cloudinary.com/dfvznarq2/image/upload/v1736018266/toyotaC3_po1ep8.png'
        ],
        cover: 'https://res.cloudinary.com/dfvznarq2/image/upload/v1736018265/toyotaC1_aq2teu.png',
        transmition: 'manual',
        fuel: 'petrol',
        isRented: false,
        isOnsale: false,
        price: 500,
        divisa: 'euro',
        bodyType: 'Sedan',
        mileage: 15000,
        color: 'White',
        trimLevel: 'SE Hybrid',
        engineCapacity: 1.8,
        doors: 4,
        passengerCapacity: 5,
        fuelConsumption: '7L/100km',
        location: 'Madrid, España',
        condition: 'Used',
        availabilityDate: '2024-11-01',
        features: ['airbags', 'ABS', 'GPS'],
        rating: 4.5,
       
    },
    {
        _id: 3,
        name: 'Corolla',
        year: 2024,
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa iste, magnam quae incidunt animi dolorum eveniet placeat corrupti!',
        brand: 'Toyota',
        model: 'Corolla',
        imgs: [
            'https://res.cloudinary.com/dfvznarq2/image/upload/v1736018265/toyotaC1_aq2teu.png', 'https://res.cloudinary.com/dfvznarq2/image/upload/v1736018266/toyotaC2_huio2n.png', 'https://res.cloudinary.com/dfvznarq2/image/upload/v1736018266/toyotaC3_po1ep8.png'
        ],
        cover: 'https://res.cloudinary.com/dfvznarq2/image/upload/v1736018265/toyotaC1_aq2teu.png',
        transmition: 'manual',
        fuel: 'petrol',
        isRented: false,
        isOnsale: false,
        price: 500,
        divisa: 'euro',
        bodyType: 'Sedan',
        mileage: 15000,
        color: 'White',
        trimLevel: 'SE Hybrid',
        engineCapacity: 1.8,
        doors: 4,
        passengerCapacity: 5,
        fuelConsumption: '7L/100km',
        location: 'Madrid, España',
        condition: 'Used',
        availabilityDate: '2024-11-01',
        features: ['airbags', 'ABS', 'GPS'],
        rating: 4.5,
       
    },
    {
        _id: 4,
        name: 'Corolla',
        year: 2024,
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa iste, magnam quae incidunt animi dolorum eveniet placeat corrupti!',
        brand: 'Toyota',
        model: 'Corolla',
        imgs: [
            'https://res.cloudinary.com/dfvznarq2/image/upload/v1736018265/toyotaC1_aq2teu.png', 'https://res.cloudinary.com/dfvznarq2/image/upload/v1736018266/toyotaC2_huio2n.png', 'https://res.cloudinary.com/dfvznarq2/image/upload/v1736018266/toyotaC3_po1ep8.png'
        ],
        cover: 'https://res.cloudinary.com/dfvznarq2/image/upload/v1736018265/toyotaC1_aq2teu.png',
        transmition: 'manual',
        fuel: 'petrol',
        isRented: false,
        isOnsale: false,
        price: 500,
        divisa: 'euro',
        bodyType: 'Sedan',
        mileage: 15000,
        color: 'White',
        trimLevel: 'SE Hybrid',
        engineCapacity: 1.8,
        doors: 4,
        passengerCapacity: 5,
        fuelConsumption: '7L/100km',
        location: 'Madrid, España',
        condition: 'Used',
        availabilityDate: '2024-11-01',
        features: ['airbags', 'ABS', 'GPS'],
        rating: 4.5,
       
    }
]


//DM Sans tipografia