// export const CAR_LIST = [
//     {
//         "_id": 1,
//         "name": "Toyota Corolla",
//         "year": 2024,
//         "description": "The 2024 Toyota Corolla offers a perfect blend of reliability, comfort, and modern design. Ideal for families or professionals, it comes with advanced features, excellent fuel efficiency, and a smooth driving experience.",
//         "brand": "Toyota",
//         "model": "Corolla",
//         "imgs": [
//             "https://res.cloudinary.com/dfvznarq2/image/upload/v1736018265/toyotaC1_aq2teu.png",
//             "https://res.cloudinary.com/dfvznarq2/image/upload/v1736018266/toyotaC2_huio2n.png",
//             "https://res.cloudinary.com/dfvznarq2/image/upload/v1736018266/toyotaC3_po1ep8.png"
//         ],
//         "cover": "https://res.cloudinary.com/dfvznarq2/image/upload/v1736018265/toyotaC1_aq2teu.png",
//         "transmition": "Automatic",
//         "fuel": "Hybrid",
//         "isRented": false,
//         "isOnsale": false,
//         "price": 499,
//         "divisa": "EUR",
//         "bodyType": "Sedan",
//         "mileage": 0,
//         "color": "Pearl White",
//         "trimLevel": "GR Sport Hybrid",
//         "engineCapacity": 1.8,
//         "doors": 4,
//         "passengerCapacity": 5,
//         "fuelConsumption": "4.5L/100km",
//         "location": "Madrid, Spain",
//         "condition": "New",
//         "availabilityDate": "2024-11-01",
//         "features": [
//             "Front and side airbags",
//             "ABS braking system",
//             "GPS navigation system",
//             "8-inch touchscreen display",
//             "Adaptive cruise control",
//             "Rearview camera",
//             "LED headlights"
//         ],
//         "rating": 4.8
//     }
//     ,
//     {
//         _id: 2,
//         name: 'Corolla',
//         year: 2024,
//         description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa iste, magnam quae incidunt animi dolorum eveniet placeat corrupti!',
//         brand: 'Toyota',
//         model: 'Corolla',
//         imgs: [
//             'https://res.cloudinary.com/dfvznarq2/image/upload/v1736018265/toyotaC1_aq2teu.png', 'https://res.cloudinary.com/dfvznarq2/image/upload/v1736018266/toyotaC2_huio2n.png', 'https://res.cloudinary.com/dfvznarq2/image/upload/v1736018266/toyotaC3_po1ep8.png'
//         ],
//         cover: 'https://res.cloudinary.com/dfvznarq2/image/upload/v1736018265/toyotaC1_aq2teu.png',
//         transmition: 'manual',
//         fuel: 'petrol',
//         isRented: false,
//         isOnsale: false,
//         price: 500,
//         divisa: 'euro',
//         bodyType: 'Sedan',
//         mileage: 15000,
//         color: 'White',
//         trimLevel: 'SE Hybrid',
//         engineCapacity: 1.8,
//         doors: 4,
//         passengerCapacity: 5,
//         fuelConsumption: '7L/100km',
//         location: 'Madrid, España',
//         condition: 'Used',
//         availabilityDate: '2024-11-01',
//         features: ['airbags', 'ABS', 'GPS'],
//         rating: 4.5,
       
//     },
//     {
//         _id: 3,
//         name: 'Corolla',
//         year: 2024,
//         description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa iste, magnam quae incidunt animi dolorum eveniet placeat corrupti!',
//         brand: 'Toyota',
//         model: 'Corolla',
//         imgs: [
//             'https://res.cloudinary.com/dfvznarq2/image/upload/v1736018265/toyotaC1_aq2teu.png', 'https://res.cloudinary.com/dfvznarq2/image/upload/v1736018266/toyotaC2_huio2n.png', 'https://res.cloudinary.com/dfvznarq2/image/upload/v1736018266/toyotaC3_po1ep8.png'
//         ],
//         cover: 'https://res.cloudinary.com/dfvznarq2/image/upload/v1736018265/toyotaC1_aq2teu.png',
//         transmition: 'manual',
//         fuel: 'petrol',
//         isRented: false,
//         isOnsale: false,
//         price: 500,
//         divisa: 'euro',
//         bodyType: 'Sedan',
//         mileage: 15000,
//         color: 'White',
//         trimLevel: 'SE Hybrid',
//         engineCapacity: 1.8,
//         doors: 4,
//         passengerCapacity: 5,
//         fuelConsumption: '7L/100km',
//         location: 'Madrid, España',
//         condition: 'Used',
//         availabilityDate: '2024-11-01',
//         features: ['airbags', 'ABS', 'GPS'],
//         rating: 4.5,
       
//     },
//     {
//         _id: 4,
//         name: 'Corolla',
//         year: 2024,
//         description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa iste, magnam quae incidunt animi dolorum eveniet placeat corrupti!',
//         brand: 'Toyota',
//         model: 'Corolla',
//         imgs: [
//             'https://res.cloudinary.com/dfvznarq2/image/upload/v1736018265/toyotaC1_aq2teu.png', 'https://res.cloudinary.com/dfvznarq2/image/upload/v1736018266/toyotaC2_huio2n.png', 'https://res.cloudinary.com/dfvznarq2/image/upload/v1736018266/toyotaC3_po1ep8.png'
//         ],
//         cover: 'https://res.cloudinary.com/dfvznarq2/image/upload/v1736018265/toyotaC1_aq2teu.png',
//         transmition: 'manual',
//         fuel: 'petrol',
//         isRented: false,
//         isOnsale: false,
//         price: 500,
//         divisa: 'euro',
//         bodyType: 'Sedan',
//         mileage: 15000,
//         color: 'White',
//         trimLevel: 'SE Hybrid',
//         engineCapacity: 1.8,
//         doors: 4,
//         passengerCapacity: 5,
//         fuelConsumption: '7L/100km',
//         location: 'Madrid, España',
//         condition: 'Used',
//         availabilityDate: '2024-11-01',
//         features: ['airbags', 'ABS', 'GPS'],
//         rating: 4.5,
       
//     }
// ]

const CAR_LIST = [

    {

        name: "Toyota Corolla",
        year: 2024,
        description: "The 2024 Toyota Corolla offers a perfect blend of reliability, comfort, and modern design. Ideal for families or professionals, it comes with advanced features, excellent fuel efficiency, and a smooth driving experience.",
        brand: "Toyota",
        model: "Corolla",
        imgs: [
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736018265/toyotaC1_aq2teu.png",
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736018266/toyotaC2_huio2n.png",
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736018266/toyotaC3_po1ep8.png"
        ],
        cover: "https://res.cloudinary.com/dfvznarq2/image/upload/v1736018265/toyotaC1_aq2teu.png",
        transmition: "Automatic",
        fuel: "Hybrid",
        isRented: false,
        isOnsale: true,
        price: 249,
        divisa: "EUR",
        bodyType: "Sedan",
        mileage: 11200,
        color: "Pearl White",
        trimLevel: "GR Sport Hybrid",
        engineCapacity: 1.8,
        doors: 4,
        passengerCapacity: 5,
        fuelConsumption: "4.2L/100km",
        location: "Madrid, Spain",
        condition: "Almost New",
        availabilityDate: "2024-11-01",
        features: [
            "Front and side airbags",
            "ABS braking system",
            "GPS navigation system",
            "8-inch touchscreen display",
            "Adaptive cruise control",
            "Rearview camera",
            "LED headlights"
        ],
        rating: 4.8
    },
    {

        name: "Ford Fiesta",
        year: 2023,
        description: "The 2023 Ford Fiesta combines compact agility with advanced technology, offering a fun and efficient driving experience. Perfect for city commutes or weekend getaways, it features modern safety systems and a stylish design.",
        brand: "Ford",
        model: "Fiesta",
        imgs: [
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736435493/Ford_F1_wq9ngq.png",
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736435495/Ford_F2_mqt97g.png",
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736435494/Ford_F3_lizy80.png",
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736435495/Ford_F4_amxz9d.png",
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736435494/Ford_F5_jtpyfm.png"
        ],
        cover: "https://res.cloudinary.com/dfvznarq2/image/upload/v1736435493/Ford_F1_wq9ngq.png",
        transmition: "Manual",
        fuel: "Petrol",
        isRented: false,
        isOnsale: true,
        price: 199,
        divisa: "EUR",
        bodyType: "Hatchback",
        mileage: 16400,
        color: "Frozen White",
        trimLevel: "Titanium",
        engineCapacity: 1.0,
        doors: 5,
        passengerCapacity: 5,
        fuelConsumption: "5.3L/100km",
        location: "Madrid, Spain",
        condition: "Used",
        availabilityDate: "2024-11-01",
        features: [
            "Airbags",
            "ABS braking system",
            "Touchscreen infotainment system",
            "Bluetooth connectivity",
            "Rearview camera",
            "Parking sensors",
            "LED daytime running lights"
        ],
        rating: 4.7
    },
    {

        name: "Volkswagen Polo",
        year: 2024,
        description: "The 2024 Volkswagen Polo is a compact hatchback that combines practicality, fuel efficiency, and advanced technology. Ideal for urban driving, it offers a stylish design, comfortable interiors, and state-of-the-art safety features.",
        brand: "Volkswagen",
        model: "Polo",
        imgs: [
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736438273/VW_P1_kmihuy.png",
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736438274/VW_P2_hny5iv.png",
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736438275/VW_P3_lzobrs.png",
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736438271/VW_P4_kr3myz.png",
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736438272/VW_P5_ooell3.png"
        ],
        cover: "https://res.cloudinary.com/dfvznarq2/image/upload/v1736438273/VW_P1_kmihuy.png",
        transmition: "Manual",
        fuel: "Petrol",
        isRented: false,
        isOnsale: false,
        price: 199,
        divisa: "EUR",
        bodyType: "Hatchback",
        mileage: 13900,
        color: "Pure White",
        trimLevel: "Life",
        engineCapacity: 1.0,
        doors: 5,
        passengerCapacity: 5,
        fuelConsumption: "5.1L/100km",
        location: "Madrid, España",
        condition: "Used",
        availabilityDate: "2024-11-01",
        features: [
            "Front airbags",
            "Side airbags",
            "ABS",
            "Adaptive Cruise Control",
            "Touchscreen infotainment system",
            "Apple CarPlay and Android Auto",
            "Rear parking sensors",
            "LED headlights",
            "Heated seats",
            "Keyless entry"
        ],
        rating: 4.6
    },
    {
        name: "Renault Twingo",
        year: 2022,
        description: "The 2024 Renault Twingo is a compact city car designed for urban living. Its compact size, easy maneuverability, and low fuel consumption make it an ideal choice for navigating tight spaces in the city. With modern tech and a fun design, it offers a playful driving experience.",
        brand: "Renault",
        model: "Twingo",
        imgs: [
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736440659/RenaultT1_mijhws.png",
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736440657/RenaultT2_beacf3.png",
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736440655/RenaultT3_lvsvqu.png",
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736440654/RenaultT5_qkaroy.png"
        ],
        cover: "https://res.cloudinary.com/dfvznarq2/image/upload/v1736440659/RenaultT1_mijhws.png",
        transmition: "Manual",
        fuel: "Petrol",
        isRented: false,
        isOnsale: true,
        price: 179,
        divisa: "EUR",
        bodyType: "Hatchback",
        mileage: 9500,
        color: "Sky Blue",
        trimLevel: "Life",
        engineCapacity: 1.0,
        doors: 3,
        passengerCapacity: 4,
        fuelConsumption: "5.1L/100km",
        location: "Madrid, España",
        condition: "Used",
        availabilityDate: "2024-11-01",
        features: [
            "Front airbags",
            "ABS",
            "Touchscreen infotainment system",
            "Bluetooth connectivity",
            "Rear parking sensors",
            "Daytime running lights",
            "Power windows",
            "Automatic climate control",
            "Cruise control"
        ],
        rating: 4.4
    },
    {
        name: "Renault Clio",
        year: 2023,
        description: "The 2024 Renault Clio is a stylish and compact hatchback that offers excellent fuel efficiency, a comfortable ride, and modern features. Ideal for city driving and everyday commutes, it combines practicality with a sleek design.",
        brand: "Renault",
        model: "Clio",
        imgs: [
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736510845/RenaultC1_msqr9j.png",
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736510845/RenaultC2_fyimxk.png",
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736510845/RenaultC3_i4gk0b.png",
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736510846/RenaultC4_qoqevn.png",
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736510846/RenaultC5_tprenn.png"
        ],
        cover: "https://res.cloudinary.com/dfvznarq2/image/upload/v1736510845/RenaultC1_msqr9j.png",
        transmition: "Manual",
        fuel: "Petrol",
        isRented: false,
        isOnsale: true,
        price: 219,
        divisa: "EUR",
        bodyType: "Hatchback",
        mileage: 5100,
        color: "Dark Grey",
        trimLevel: "Zen",
        engineCapacity: 1.0,
        doors: 5,
        passengerCapacity: 5,
        fuelConsumption: "5.0L/100km",
        location: "Madrid, España",
        condition: "New",
        availabilityDate: "2024-11-01",
        features: [
            "Front airbags",
            "ABS",
            "Touchscreen infotainment system",
            "Bluetooth connectivity",
            "Rear parking sensors",
            "Daytime running lights",
            "Power windows",
            "Automatic climate control",
            "Lane departure warning"
        ],
        rating: 4.6
    },
    {
        name: "Seat Ibiza",
        year: 2023,
        description: "The 2024 Seat Ibiza is a stylish compact car perfect for city driving. With its modern features and comfortable ride, it offers excellent efficiency and a fun driving experience.",
        brand: "Seat",
        model: "Ibiza",
        imgs: [
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736510989/SeatI1_efza2u.png",
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736511052/SeatI2_wjb0o6.png",
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736511116/SeatI3_hjrj98.png",
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736511180/SeatI4_f7wndv.png",
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736511243/SeatI5_tz9qc7.png"
        ],
        cover: "https://res.cloudinary.com/dfvznarq2/image/upload/v1736510989/SeatI1_efza2u.png",
        transmition: "Manual",
        fuel: "Petrol",
        isRented: false,
        isOnsale: true,
        price: 169,
        divisa: "EUR",
        bodyType: "Hatchback",
        mileage: 8100,
        color: "Black",
        trimLevel: "Style",
        engineCapacity: 1.2,
        doors: 5,
        passengerCapacity: 5,
        fuelConsumption: "5.2L/100km",
        location: "Madrid, España",
        condition: "Used",
        availabilityDate: "2024-11-01",
        features: [
            "Front airbags",
            "ABS",
            "Touchscreen infotainment system",
            "Bluetooth connectivity",
            "Rear parking sensors",
            "Daytime running lights",
            "Power windows",
            "Automatic climate control",
            "Cruise control"
        ],
        rating: 4.5
    },
    {

        name: "Seat Arona",
        year: 2023,
        description: "The 2024 Seat Arona offers a practical yet stylish experience with a compact build that's perfect for urban environments. With an efficient engine and a range of tech features, it delivers a great driving experience while ensuring excellent fuel economy.",
        brand: "Seat",
        model: "Arona",
        imgs: [
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736510886/SeatA1_krglzc.png",
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736510887/SeatA2_wfcdbn.png",
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736510888/SeatA3_jygsdu.png",
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736510889/SeatA4_tfcc9p.png",
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736510924/SeatA5_wl2dba.png"
        ],
        cover: "https://res.cloudinary.com/dfvznarq2/image/upload/v1736510886/SeatA1_krglzc.png",
        transmition: "Manual",
        fuel: "Petrol",
        isRented: false,
        isOnsale: false,
        price: 210,
        divisa: "EUR",
        bodyType: "SUV",
        mileage: 13500,
        color: "Light Gray",
        trimLevel: "Xperience",
        engineCapacity: 1.0,
        doors: 5,
        passengerCapacity: 5,
        fuelConsumption: "5.5L/100km",
        location: "Madrid, España",
        condition: "Used",
        availabilityDate: "2024-11-01",
        features: [
            "Front airbags",
            "ABS",
            "Touchscreen infotainment system",
            "Bluetooth connectivity",
            "Rear parking sensors",
            "Daytime running lights",
            "Power windows",
            "Automatic climate control"
        ],
        rating: 4.5
    }
    ,
    {

        name: "Fiat Panda",
        year: 2024,
        description: "Compact, efficient, and stylish, the Fiat Panda offers a versatile experience. Ideal for both city driving and weekend getaways, this car combines practicality with fun driving dynamics. Its modern tech and spacious cabin make it a favorite choice among urban drivers.",
        brand: "Fiat",
        model: "Panda",
        imgs: [
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736510880/FiatP1_lcdsbz.png",
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736510881/FiatP2_kc76e4.png",
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736510882/FiatP3_jpmmin.png",
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736510883/FiatP4_hbkky3.png",
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736510885/FiatP5_czfse7.png"
        ],
        cover: "https://res.cloudinary.com/dfvznarq2/image/upload/v1736510880/FiatP1_lcdsbz.png",
        transmition: "Manual",
        fuel: "Petrol",
        isRented: false,
        isOnsale: true,
        price: 170,
        divisa: "EUR",
        bodyType: "Hatchback",
        mileage: 5400,
        color: "Pearl White",
        trimLevel: "Pop",
        engineCapacity: 0.9,
        doors: 5,
        passengerCapacity: 4,
        fuelConsumption: "4.5L/100km",
        location: "Barcelona, España",
        condition: "New",
        availabilityDate: "2024-11-01",
        features: [
            "Front airbags",
            "ABS",
            "Touchscreen infotainment system",
            "Bluetooth connectivity",
            "Rear parking sensors",
            "Daytime running lights",
            "Power windows"
        ],
        rating: 4.0
    },
    {

        name: "Hyundai i30",
        year: 2024,
        description: "The 2024 Hyundai i30 offers a balance of comfort, performance, and safety. With its sleek design, powerful engine options, and excellent fuel efficiency, the i30 is an ideal choice for those who want practicality without sacrificing driving pleasure.",
        brand: "Hyundai",
        model: "i30",
        imgs: [
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736510876/Hyundai1_iasrlo.png",
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736510877/Hyundai2_yf6nko.png",
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736510878/Hyundai3_abmsir.png"
        ],
        cover: "https://res.cloudinary.com/dfvznarq2/image/upload/v1736510876/Hyundai1_iasrlo.png",
        transmition: "Manual",
        fuel: "Petrol",
        isRented: false,
        isOnsale: true,
        price: 230,
        divisa: "EUR",
        bodyType: "Hatchback",
        mileage: 7100,
        color: "Metallic Silver",
        trimLevel: "Premium",
        engineCapacity: 1.4,
        doors: 5,
        passengerCapacity: 5,
        fuelConsumption: "5.8L/100km",
        location: "Valencia, España",
        condition: "Used",
        availabilityDate: "2024-11-01",
        features: [
            "Front airbags",
            "ABS",
            "Touchscreen infotainment system",
            "Bluetooth connectivity",
            "Rear parking sensors",
            "Daytime running lights",
            "Power windows",
            "Automatic climate control"
        ],
        rating: 4.6
    },
    {

        name: "Ford Puma",
        year: 2024,
        description: "The Ford Puma combines an efficient engine with a sporty design. It delivers dynamic performance, advanced technology, and top-notch safety features. Perfect for those who want both style and practicality.",
        brand: "Ford",
        model: "Puma",
        imgs: [
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736510867/Puma1_qrhmse.png",
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736510868/Puma2_qyjrfl.png",
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736510869/Puma3_nkmqx2.png",
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736510870/Puma4_ooft5p.png"
        ],
        cover: "https://res.cloudinary.com/dfvznarq2/image/upload/v1736510867/Puma1_qrhmse.png",
        transmition: "Automatic",
        fuel: "Petrol",
        isRented: false,
        isOnsale: false,
        price: 250,
        divisa: "EUR",
        bodyType: "SUV",
        mileage: 10200,
        color: "Dark Blue",
        trimLevel: "Titanium",
        engineCapacity: 1.0,
        doors: 5,
        passengerCapacity: 5,
        fuelConsumption: "6.1L/100km",
        location: "Madrid, España",
        condition: "Used",
        availabilityDate: "2024-11-01",
        features: [
            "Front airbags",
            "ABS",
            "Touchscreen infotainment system",
            "Bluetooth connectivity",
            "Rear parking sensors",
            "Daytime running lights",
            "Power windows",
            "Automatic climate control"
        ],
        rating: 4.7
    },
    {

        name: "Fiat 500e",
        year: 2024,
        description: "The Fiat 500e combines retro charm with modern electric efficiency. Perfect for city dwellers, it offers easy handling and zero-emission driving, making it a great choice for those who prioritize eco-friendliness and style.",
        brand: "Fiat",
        model: "500e",
        imgs: [
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736510862/Fiat1_r4vrh0.png",
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736510863/Fiat2_elmyme.png",
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736510864/Fiat3_j70qjt.png",
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736510865/Fiat4_xks48d.png",
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736510866/Fiat5_zgqx8u.png"
        ],
        cover: "https://res.cloudinary.com/dfvznarq2/image/upload/v1736510862/Fiat1_r4vrh0.png",
        transmition: "Automatic",
        fuel: "Electric",
        isRented: false,
        isOnsale: false,
        price: 170,
        divisa: "EUR",
        bodyType: "Hatchback",
        mileage: 5000,
        color: "Pearl White",
        trimLevel: "La Prima",
        engineCapacity: 0,
        doors: 3,
        passengerCapacity: 4,
        fuelConsumption: "N/A",
        location: "Madrid, España",
        condition: "New",
        availabilityDate: "2024-11-01",
        features: [
            "Front airbags",
            "ABS",
            "Touchscreen infotainment system",
            "Bluetooth connectivity",
            "Rear parking sensors",
            "Daytime running lights",
            "Power windows",
            "Automatic climate control"
        ],
        rating: 4.4
    }
    ,
    {

        name: "Hyundai i20",
        year: 2024,
        description: "The 2024 Hyundai i20 is a compact city car designed for urban living. It combines modern features with great maneuverability, perfect for navigating city streets. With its stylish look and efficient engine, it offers both practicality and fun for everyday driving.",
        brand: "Hyundai",
        model: "i20",
        imgs: [
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736510871/Hyundai1_zfrqj8.png",
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736510873/Hyundai2_mn8zaq.png",
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736510874/Hyundai3_xmqecp.png"
        ],
        cover: "https://res.cloudinary.com/dfvznarq2/image/upload/v1736510871/Hyundai1_zfrqj8.png",
        transmition: "Manual",
        fuel: "Petrol",
        isRented: false,
        isOnsale: false,
        price: 199,
        divisa: "EUR",
        bodyType: "Hatchback",
        mileage: 12000,
        color: "White",
        trimLevel: "Comfort",
        engineCapacity: 1.2,
        doors: 5,
        passengerCapacity: 5,
        fuelConsumption: "5.4L/100km",
        location: "Madrid, España",
        condition: "Used",
        availabilityDate: "2024-11-01",
        features: [
            "Front airbags",
            "ABS",
            "Touchscreen infotainment system",
            "Bluetooth connectivity",
            "Rear parking sensors",
            "Daytime running lights",
            "Power windows",
            "Automatic climate control",
            "Cruise control",
            "LED headlights"
        ],
        rating: 4.2
    }

];



module.exports = { CAR_LIST };
//DM Sans tipografia