export const CAR_LIST = [
    {
        "_id": 1,
        "name": "Toyota Corolla",
        "year": 2024,
        "description": "The 2024 Toyota Corolla offers a perfect blend of reliability, comfort, and modern design. Ideal for families or professionals, it comes with advanced features, excellent fuel efficiency, and a smooth driving experience.",
        "brand": "Toyota",
        "model": "Corolla",
        "imgs": [
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736018265/toyotaC1_aq2teu.png",
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736018266/toyotaC2_huio2n.png",
            "https://res.cloudinary.com/dfvznarq2/image/upload/v1736018266/toyotaC3_po1ep8.png"
        ],
        "cover": "https://res.cloudinary.com/dfvznarq2/image/upload/v1736018265/toyotaC1_aq2teu.png",
        "transmition": "Automatic",
        "fuel": "Hybrid",
        "isRented": false,
        "isOnsale": false,
        "price": 499,
        "divisa": "EUR",
        "bodyType": "Sedan",
        "mileage": 0,
        "color": "Pearl White",
        "trimLevel": "GR Sport Hybrid",
        "engineCapacity": 1.8,
        "doors": 4,
        "passengerCapacity": 5,
        "fuelConsumption": "4.5L/100km",
        "location": "Madrid, Spain",
        "condition": "New",
        "availabilityDate": "2024-11-01",
        "features": [
            "Front and side airbags",
            "ABS braking system",
            "GPS navigation system",
            "8-inch touchscreen display",
            "Adaptive cruise control",
            "Rearview camera",
            "LED headlights"
        ],
        "rating": 4.8
    }
    ,
    {
        _id: 2,
        name: 'Corolla',
        year: 2024,
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa iste, magnam quae incidunt animi dolorum eveniet placeat corrupti!',
        brand: 'Toyota',
        model: 'Corolla',
        imgs: [
            'https://res.cloudinary.com/dfvznarq2/image/upload/v1736018265/toyotaC1_aq2teu.png', 'https://res.cloudinary.com/dfvznarq2/image/upload/v1736018266/toyotaC2_huio2n.png', 'https://res.cloudinary.com/dfvznarq2/image/upload/v1736018266/toyotaC3_po1ep8.png'
        ],
        cover: 'https://res.cloudinary.com/dfvznarq2/image/upload/v1736018265/toyotaC1_aq2teu.png',
        transmition: 'manual',
        fuel: 'petrol',
        isRented: false,
        isOnsale: false,
        price: 500,
        divisa: 'euro',
        bodyType: 'Sedan',
        mileage: 15000,
        color: 'White',
        trimLevel: 'SE Hybrid',
        engineCapacity: 1.8,
        doors: 4,
        passengerCapacity: 5,
        fuelConsumption: '7L/100km',
        location: 'Madrid, España',
        condition: 'Used',
        availabilityDate: '2024-11-01',
        features: ['airbags', 'ABS', 'GPS'],
        rating: 4.5,
       
    },
    {
        _id: 3,
        name: 'Corolla',
        year: 2024,
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa iste, magnam quae incidunt animi dolorum eveniet placeat corrupti!',
        brand: 'Toyota',
        model: 'Corolla',
        imgs: [
            'https://res.cloudinary.com/dfvznarq2/image/upload/v1736018265/toyotaC1_aq2teu.png', 'https://res.cloudinary.com/dfvznarq2/image/upload/v1736018266/toyotaC2_huio2n.png', 'https://res.cloudinary.com/dfvznarq2/image/upload/v1736018266/toyotaC3_po1ep8.png'
        ],
        cover: 'https://res.cloudinary.com/dfvznarq2/image/upload/v1736018265/toyotaC1_aq2teu.png',
        transmition: 'manual',
        fuel: 'petrol',
        isRented: false,
        isOnsale: false,
        price: 500,
        divisa: 'euro',
        bodyType: 'Sedan',
        mileage: 15000,
        color: 'White',
        trimLevel: 'SE Hybrid',
        engineCapacity: 1.8,
        doors: 4,
        passengerCapacity: 5,
        fuelConsumption: '7L/100km',
        location: 'Madrid, España',
        condition: 'Used',
        availabilityDate: '2024-11-01',
        features: ['airbags', 'ABS', 'GPS'],
        rating: 4.5,
       
    },
    {
        _id: 4,
        name: 'Corolla',
        year: 2024,
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa iste, magnam quae incidunt animi dolorum eveniet placeat corrupti!',
        brand: 'Toyota',
        model: 'Corolla',
        imgs: [
            'https://res.cloudinary.com/dfvznarq2/image/upload/v1736018265/toyotaC1_aq2teu.png', 'https://res.cloudinary.com/dfvznarq2/image/upload/v1736018266/toyotaC2_huio2n.png', 'https://res.cloudinary.com/dfvznarq2/image/upload/v1736018266/toyotaC3_po1ep8.png'
        ],
        cover: 'https://res.cloudinary.com/dfvznarq2/image/upload/v1736018265/toyotaC1_aq2teu.png',
        transmition: 'manual',
        fuel: 'petrol',
        isRented: false,
        isOnsale: false,
        price: 500,
        divisa: 'euro',
        bodyType: 'Sedan',
        mileage: 15000,
        color: 'White',
        trimLevel: 'SE Hybrid',
        engineCapacity: 1.8,
        doors: 4,
        passengerCapacity: 5,
        fuelConsumption: '7L/100km',
        location: 'Madrid, España',
        condition: 'Used',
        availabilityDate: '2024-11-01',
        features: ['airbags', 'ABS', 'GPS'],
        rating: 4.5,
       
    }
]


//DM Sans tipografia